export const StudentListExcelTableHeader = [
  "ID",
  "Username",
  "Email",
  "Identify Number",
  "Khmer Full Name",
  "English Full Name",
  "Gender",
  "Student Status",
  "Date of Birth",
  "Phone Number",
  "Class",
  "Status",
  "Created At",
];
