spring:
  application:
    name: ks_it_school

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          time_zone: Asia/Phnom_Penh
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  jackson:
    time-zone: Asia/Phnom_Penh
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

jwt:
  secret:
    key: da2bd42bef8f9f957d647ed13571d35b59c7055fb723eacdb05154878da17d77d3180385fc232cab38bded0fc7dbda0d439cc275e91164ade266d64d50633bc7
  expiration-min: 9999999999999

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.menghor.ksit

logging:
  level:
    root: INFO
    com.menghor.ksit: INFO
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.apache.catalina: WARN
    org.apache.tomcat: WARN
    org.apache.coyote: WARN
    com.github.benmanes.caffeine: WARN
    io.lettuce.core: WARN
    com.zaxxer.hikari: WARN