// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCl0BHgFJpuePn6niIxfG6Jo4y9WIckE',
    appId: '1:45539224275:web:e8dabb672bdf927b954226',
    messagingSenderId: '45539224275',
    projectId: 'ksit-dev',
    authDomain: 'ksit-dev.firebaseapp.com',
    storageBucket: 'ksit-dev.firebasestorage.app',
    measurementId: 'G-CNQ4YFK2EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBseXGdQCOADedtVZ3vhksprLvHMaXHYoo',
    appId: '1:45539224275:android:87353de061c1211f954226',
    messagingSenderId: '45539224275',
    projectId: 'ksit-dev',
    storageBucket: 'ksit-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC_18k3Ihtp65dBGNjoqJyHAmX0dShqT4',
    appId: '1:45539224275:ios:4a10296fe5c98343954226',
    messagingSenderId: '45539224275',
    projectId: 'ksit-dev',
    storageBucket: 'ksit-dev.firebasestorage.app',
    iosBundleId: 'com.example.ksitMobile',
  );
}
